version: "3.8"

services:
  db:
    image: postgres
    container_name: go-postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis
    ports:
      - 6379:6379

  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ".:/app"
    restart: always
    depends_on:
      - db
    links:
      - "db:database"
